# ==============================================================================
# jc-hyprland-dotfiles
# Theme: Cyber Noir
# Hyprland palette
# ==============================================================================

$theme_bg          = rgba(090b10ff)
$theme_bg_alt      = rgba(0f131aff)

$theme_surface     = rgba(151a22ff)
$theme_surface_alt = rgba(212936ff)

$theme_foreground  = rgba(d8dee9ff)
$theme_muted       = rgba(6b7482ff)

$theme_primary     = rgba(00e5ffff)
$theme_secondary   = rgba(ff3cacff)
$theme_accent      = rgba(7cff6bff)

$theme_green       = rgba(4cff9aff)
$theme_yellow      = rgba(ffe66dff)
$theme_red         = rgba(ff4d6dff)

$theme_shadow      = rgba(05070bcc)