# ==============================================================================
# jc-hyprland-dotfiles
# Theme: Cyber Noir
# Foot palette
# ==============================================================================

[colors-dark]

foreground=d8dee9
background=090b10

alpha=0.84
alpha-mode=matching

cursor=090b10 00e5ff

selection-foreground=090b10
selection-background=00e5ff

urls=00e5ff

search-box-no-match=090b10 ff4d6d
search-box-match=090b10 4cff9a

scrollback-indicator=090b10 ff3cac


# ANSI

regular0=212936
regular1=ff4d6d
regular2=4cff9a
regular3=ffe66d
regular4=00b8ff
regular5=ff3cac
regular6=21d4b4
regular7=aeb8c7

bright0=495364
bright1=ff758f
bright2=7cffb1
bright3=fff09a
bright4=62d7ff
bright5=ff79d1
bright6=5fffe0
bright7=d8dee9