# ==============================================================================
# jc-hyprland-dotfiles
# Hyprland integration bridge
# ==============================================================================

# Active theme
source = ~/.config/jc-hyprland-dotfiles/theme/colors.conf

# Appearance
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/appearance.conf

# Animations
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/animations.conf

# Autostart
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/autostart.conf

# User overrides MUST remain last
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/keybindings.conf