# ==============================================================================
# jc-hyprland-dotfiles
# Hyprland integration bridge
# ==============================================================================


# Theme
source = ~/.config/jc-hyprland-dotfiles/repo/themes/odyssey-glass/colors.conf


# Appearance
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/appearance.conf


# Animations
source = ~/.config/jc-hyprland-dotfiles/repo/config/hypr/hyprlang/common/animations.conf