# ==============================================================================
# jc-hyprland-dotfiles
# Theme: Odyssey Glass
# Hyprland palette
# ==============================================================================

$theme_bg          = rgba(11111bff)
$theme_bg_alt      = rgba(181825ff)

$theme_surface     = rgba(1e1e2eff)
$theme_surface_alt = rgba(313244ff)

$theme_foreground  = rgba(cdd6f4ff)
$theme_muted       = rgba(6c7086ff)

$theme_primary     = rgba(89b4faff)
$theme_secondary   = rgba(cba6f7ff)
$theme_accent      = rgba(74c7ecff)

$theme_green       = rgba(a6e3a1ff)
$theme_yellow      = rgba(f9e2afff)
$theme_red         = rgba(f38ba8ff)

$theme_shadow      = rgba(11111b99)