# ==============================================================================
# jc-hyprland-dotfiles
# Theme: Odyssey Glass
# Hyprland palette
# ==============================================================================

$odyssey_bg          = rgba(11111bff)
$odyssey_bg_alt      = rgba(181825ff)

$odyssey_surface     = rgba(1e1e2eff)
$odyssey_surface_alt = rgba(313244ff)

$odyssey_foreground  = rgba(cdd6f4ff)
$odyssey_muted       = rgba(6c7086ff)

$odyssey_primary     = rgba(89b4faff)
$odyssey_secondary   = rgba(cba6f7ff)
$odyssey_accent      = rgba(74c7ecff)

$odyssey_green       = rgba(a6e3a1ff)
$odyssey_yellow      = rgba(f9e2afff)
$odyssey_red         = rgba(f38ba8ff)

$odyssey_shadow      = rgba(11111b99)