$od_bg = rgba(11111bcc)
$od_surface = rgba(181825e6)
$od_surface2 = rgba(1e1e2ef2)
$od_text = rgb(cdd6f4)
$od_muted = rgb(6c7086)
$od_primary = rgb(89b4fa)
$od_secondary = rgb(cba6f7)
$od_accent = rgb(74c7ec)
$od_success = rgb(a6e3a1)
$od_warning = rgb(f9e2af)
$od_critical = rgb(f38ba8)
