# ==============================================================================
# jc-hyprland-dotfiles
# Theme: Odyssey Glass
# Foot palette
# ==============================================================================

[colors-dark]

foreground=cdd6f4
background=11111b

alpha=0.82
alpha-mode=matching

cursor=11111b 89b4fa

selection-foreground=11111b
selection-background=89b4fa

urls=74c7ec

search-box-no-match=11111b f38ba8
search-box-match=11111b a6e3a1

scrollback-indicator=11111b 89b4fa

regular0=45475a
regular1=f38ba8
regular2=a6e3a1
regular3=f9e2af
regular4=89b4fa
regular5=cba6f7
regular6=94e2d5
regular7=bac2de

bright0=585b70
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4fa
bright5=cba6f7
bright6=89dceb
bright7=cdd6f4